.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "TEXTSUGGEST" "1" "July 2016" "" ""
.
.SH "NAME"
\fBtextsuggest\fR \-\- X11 utility to autocomplete words in the GUI
.
.SH "SYNOPSIS"
  \fBtextsuggest\fR [\fB\-\-help\fR] [\fB\-\-word\fR \fIword\fR] [\fB\-\-plainrofi\fR] [\fB\-\-font\fR \fIfont\fR] [\fB\-\-nohistory\fR] [\fB\-\-language\fR \fIfont\fR] [\fB\-\-noselect\fR]
.
.SH "DESCRIPTION"
  https://github\.com/bharadwaj\-raju/TextSuggest
.
.P
  textsuggest is a simple X11 utility that autocompletes, suggests and expands words in the GUI\.
.
.SH "USAGE"
  textsuggest has two modes:
.
.IP "\(bu" 4
\'replace\' mode: Suggests word completions based on current X11 selection contents\. Default\.
.
.IP "\(bu" 4
\'insert\' mode : Gives a list of all known words, allowing you to search them and choose one\. Activated with \fB\-\-noselect\fR option\.
.
.IP
Thus, assign two keyboard shortcuts:
.
.IP "\(bu" 4
\fBtextsuggest\fR for replace mode
.
.IP "\(bu" 4
\fBtextsuggest \-\-noselect\fR for insert mode
.
.IP "" 0
.
.SH "OPTIONS"
  \fB\-\-help\fR, \fB\-h\fR
   View a short summary of options
.
.P
   \fB\-\-word\fR \fIword\fR
   Instead of suggesting words based on X11 selection contents, suggest based on \fIword\fR specified\. Ignored if \fB\-\-noselect\fR\|\.
.
.P
  \fB\-\-autosel *[beginning|middle|end]*\fR
.
.P
  Automatically select words for you before suggestion, saving time and (your) keystrokes\. Ignored if \fB\-\-noselect\fR\|\.
.
.P
  \fB\-\-autosel\fR has three modes:
.
.IP "\(bu" 4
\'beginning\': Assumes text\-cursor is at beginning of word\.
.
.IP "\(bu" 4
\'middle\'   : Assumes text\-cursor is somewhere in the middle of word\.
.
.IP "\(bu" 4
\'end\'      : Assumes text\-cursor is at end of word\. Default\.
.
.IP
The three choices help choose the keyboard shortcut to be pressed\. It would be good to auto\-detect the option
according to the text\-cursor\'s position, but X11 does not provide this\.
.
.IP "" 0
.
.P
\fBNOTE:\fR The normal "you select text and textsuggests suggests on that" will \fBnot\fR work with this enabled\.
.
.P
   \fB\-\-plainrofi\fR
   Do not apply custom Rofi theme\.
.
.P
   \fB\-\-font\fR \fIfont\fR
   Instead of selecting font based on language (default: Monospace 10), use \fIfont\fR specified\. \fIfont\fR must be in Pango format: \fBFontName (Weight) Size\fR
.
.P
   \fB\-\-nohistory\fR
   Disable frequently\-used words history (stored in \fB~/\.config/textsuggest/history\.txt\fR)
.
.P
   \fB\-\-language\fR \fIlanguage\fR
   Instead of auto\-detecting language based on keyboard layout, use \fIlanguage\fR specified\.
.
.SH "OTHER LANGUAGES"
  By default, English and Bangla dictionaries are provided\. To add support for other languages, follow these steps:
.
.IP "\(bu" 4
Get a suitable dictionary/wordlist for your language\. Search for \'<your language> wordlist\' online\.
.
.IP "\(bu" 4
After downloading said dictionary (which should be in this format: a \fB<your language>\fR directory, with one or more text files with words in them), move it into \fB/usr/share/textsuggest\fR directory\.
.
.IP
You\'re done\. The language should be auto\-detected, otherwise set langauge with \fB\-\-language\fR\|\. A suitable font should also be auto\-detected, otherwise set font with \fB\-\-font\fR\|\.
.
.IP "" 0
.
.SH "BUGS AND FEATURE REQUESTS"
  Please file bug reports and feature requests at the GitHub repository: https://github\.com/bharadwaj\-raju/TextSuggest