.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "TEXTSUGGEST" "1" "September 2016" "" ""
.
.SH "NAME"
\fBtextsuggest\fR \-\- X11 utility to autocomplete words in the GUI
.
.SH "SYNOPSIS"
  \fBtextsuggest\fR [\fB\-\-help\fR] [\fB\-\-word\fR \fIword\fR \.\.\.] [\fB\-\-no\-rofi\-customization\fR] [\fB\-\-font\fR \fIfont\fR] [\fB\-\-no\-history\fR] [\fB\-\-language\fR \fIlanguage\fR] [\fB\-\-no\-selection\fR]
.
.SH "DESCRIPTION"
  https://github\.com/bharadwaj\-raju/TextSuggest
.
.P
  textsuggest (or TextSuggest) is a simple X11 utility that saves you keystrokes by autocompleting, suggesting and expanding words\.
.
.SH "USAGE"
  Call \fBtextsuggest\fR to get suggestions, completions etc\. See also the \fBOPTIONS\fR section\.
.
.P
  For convenience, bind the script to a keyboard shortcut(s):
.
.IP "\(bu" 4
\fBtextsuggest\fR for replace mode (suggestions for a specific word, taken from X11 selection (see \fBxsel(1)\fR) if \fB\-\-word\fR is not given)
.
.IP "\(bu" 4
\fBtextsuggest \-\-all\-words\fR for insert mode (get all words)
.
.IP
Also see the \fBAUTO\-SELECTION\fR section\.
.
.IP "" 0
.
.SH "OPTIONS"
  \fB\-h\fR, \fB\-\-help\fR            show a summary of options and exit
.
.P
  \fB\-\-word\fR \fIword\fR \.\.\.
                        Specify word to give suggestions for\. Default: taken from X11 clipboard\. Ignored if \-\-no\-selection\.
.
.P
  \fB\-\-all\-words\fR
                        Give all words as suggestions, which you can then filter\.
.
.P
  \fB\-\-font\fR \fIfont\fR
                        Specify font for Rofi\. Must be in Pango format: FontName (Weight (optional) FontSize)\.
.
.P
  \fB\-\-no\-history\fR          Disable the frequently\-used words history (stored in ~/\.config/textsuggest/history\.txt)
.
.P
  \fB\-\-exit\-if\-no\-words\-found\fR
                        Exit if no words are found (instead of restarting in \-\-no\-selection mode)
.
.P
  \fB\-\-language\fR \fIlanguages\fR \.\.\.   Manually set language(s), in case script fails to auto\-detect from keyboard layout\.
.
.P
  \fB\-\-auto\-selection\fR \fI[beginning|middle|end]\fR
                        Automatically select word under cursor and suggest\. See \fBAUTO\-SELECTION\fR\|\. Ignored if \-\-no\-selection\.
.
.P
  \fB\-\-no\-processing\fR       Disable using of any processors\.
.
.P
  \fB\-\-rofi\-options\fR \fIoptions\fR \.\.\.
                        Specify additonal options to pass to Rofi\.
.
.P
  \fB\-\-force\-gtk3\-fix\fR		Always use the GTK+ 3 workaround\. If not specified, it is detected whether use is applicable\.
.
.P
  \fB\-v\fR, \fB\-\-version\fR         Print version and license information\.
.
.SH "EXPANSIONS"
  \fBCOMMANDS\fR
.
.P
  Use \fB#command\fR in TextSuggest to type out the output of \fBcommand\fR\|\.
.
.P
  \fBMATH\fR
.
.P
  Use \fB%2+3\fR in TextSuggest to insert the answer of \fB2+3\fR\|\. Can be used with any math valid in \fBpython3(1)\fR, in addition to its \fBmath\fR library\.
.
.P
  \fBALIASES\fR
.
.P
  Define them in \fB~/\.config/textsuggest/Custom_Words\.txt\fR:
.
.P
  short=really long text!
.
.P
  Can be combined with \fBCOMMANDS\fR and \fBMATH\fR above\.
.
.SH "OTHER LANGUAGES"
  By default, English and Bangla dictionaries are provided\. To add support for other languages, follow these steps:
.
.IP "\(bu" 4
Get a suitable dictionary/wordlist for your language\. Search for \'<your language> wordlist\' online\.
.
.IP "\(bu" 4
After downloading said dictionary (which should be in this format: a \fB<your language>\fR directory, with one or more text files with words in them), move it into \fB/usr/share/textsuggest\fR directory\.
.
.IP
You\'re done\. The language should be auto\-detected, otherwise set langauge with \fB\-\-language\fR\|\. A suitable font should also be auto\-detected, otherwise set font with \fB\-\-font\fR\|\.
.
.IP "" 0
.
.SH "RETURN CODES"
.
.IP "\(bu" 4
0 : Success
.
.IP "\(bu" 4
1 : No words found
.
.IP "\(bu" 4
2 : Cancelled by user
.
.IP "" 0
.
.SH "AUTO\-SELECTION"
  Automatically select word under cursor for you before suggestion, saving time and keystrokes\.
.
.P
  \fB\-\-auto\-selection\fR has three modes:
.
.IP "\(bu" 4
\'beginning\': Assumes text\-cursor is at beginning of word\.
.
.IP "\(bu" 4
\'middle\'   : Assumes text\-cursor is somewhere in the middle of word\.
.
.IP "\(bu" 4
\'end\'      : Assumes text\-cursor is at end of word\. Default\.
.
.IP
The three choices help choose the keyboard shortcut to be pressed\. It would be good to auto\-detect the option
according to the text\-cursor\'s position, but X11 does not provide this\.
.
.IP
\fBNOTE:\fR The normal "you select text and textsuggests suggests on that" will \fBnot\fR work with this enabled\.
.
.IP "" 0
.
.SH "EXTENSIONS"
  TextSuggest supports powerful extensions via it\'s \fIprocessors\fR\|\.
.
.P
  A processor does changes to the word chosen by the user and returns it to TextSuggest to type out\.
.
.P
  TextSuggest includes two processors by default: \fBcommand\fR and \fBmath_expression\fR (see \fBEXPANSIONS\fR)\.
.
.P
  \fBMaking your own\fR
.
.P
  A processor is simply a \fBpython3(1)\fR script that defines at least two functions:
.
.IP "\(bu" 4
\fBmatches(text)\fR: Return if \fBtext\fR should be processed or not (processor\'s choice)
.
.IP "\(bu" 4
\fBprocess(text)\fR: Return a string containing changed/modified \fBtext\fR
.
.IP
Optionally it may define a \fBprocess_all\fR variable, whose valuse may be:
.
.IP "\(bu" 4
\fB"first"\fR: To first process text through this processor before any others\.
.
.IP "\(bu" 4
\fB"last"\fR: After all processors have processed, process the text through this
.
.IP "" 0
.
.SH "BUGS AND FEATURE REQUESTS"
  Please file bug reports and feature requests at the GitHub repository: https://github\.com/bharadwaj\-raju/TextSuggest/issues
.
.P
  Please include the output of \fBtextsuggest \-\-version\fR in the report/request\.
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
\fBtextsuggestd(1)\fR
.
.IP "\(bu" 4
\fBxsel(1)\fR
.
.IP "\(bu" 4
\fBxdotool(1)\fR
.
.IP "\(bu" 4
\fBpython3(1)\fR
.
.IP "" 0
